const fs = require('fs');
const path = require('path');

const faqsTranslations = {
  en: [
    { question: "Are these SEO tools really free?", answer: "Yes! All tools on SEO Utilities are completely free to use with no sign-up required. We support the site through non-intrusive advertisements." },
    { question: "Is my data safe? Do you store any information?", answer: "Absolutely. All tools run entirely in your browser. We never send your data to any server, and nothing is stored or logged. Your content stays private." },
    { question: "What SEO tools are available?", answer: "We offer 17+ tools including Meta Tag Generator, Schema Markup Generator, Sitemap Generator, Robots.txt Generator, Keyword Density Checker, QR Code Generator, code minifiers, and many more. Each tool is designed to help with a specific aspect of SEO." },
    { question: "Can I use these tools for commercial projects?", answer: "Yes, you can use the output generated by our tools for any purpose, including commercial projects. There are no restrictions on how you use the generated code or content." },
    { question: "How do I improve my website's SEO?", answer: "Start with proper meta tags (use our Meta Tag Generator), add structured data (Schema Markup Generator), create a sitemap (Sitemap Generator), and ensure your robots.txt is properly configured. Each tool page includes specific SEO tips to help you get started." },
    { question: "Do these tools work on mobile devices?", answer: "Yes! All tools are fully responsive and work perfectly on desktop, tablet, and mobile devices. The interface adapts to your screen size for the best experience." }
  ],
  es: [
    { question: "¿Son realmente gratuitas estas herramientas SEO?", answer: "¡Sí! Todas las herramientas son de uso gratuito sin registro previo. Mantenemos el sitio mediante anuncios no intrusivos." },
    { question: "¿Mis datos están seguros? ¿Almacenan alguna información?", answer: "Absolutamente. Todas las herramientas se ejecutan en tu navegador. Nunca enviamos tus datos a ningún servidor y nada se almacena. Tu contenido es privado." },
    { question: "¿Qué herramientas SEO están disponibles?", answer: "Ofrecemos más de 17 herramientas incluyendo Generador de Meta Tags, Generador de Schema, Generador de Sitemap, Robots.txt, y muchas más." },
    { question: "¿Puedo usar estas herramientas para proyectos comerciales?", answer: "Sí, puedes usar el código generado para cualquier propósito, incluyendo proyectos comerciales. No hay restricciones." },
    { question: "¿Cómo mejoro el SEO de mi sitio web?", answer: "Empieza con etiquetas meta adecuadas, añade datos estructurados, crea un sitemap y asegúrate de que tu robots.txt está bien configurado." },
    { question: "¿Funcionan estas herramientas en dispositivos móviles?", answer: "¡Sí! Todas las herramientas son responsivas y funcionan perfectamente en escritorio, tablet y móvil." }
  ],
  fr: [
    { question: "Ces outils SEO sont-ils vraiment gratuits ?", answer: "Oui ! Tous les outils sont gratuits sans inscription. Nous soutenons le site par des publicités non intrusives." },
    { question: "Mes données sont-elles en sécurité ?", answer: "Absolument. Tous les outils s'exécutent dans votre navigateur. Nous n'envoyons jamais vos données sur nos serveurs. Votre contenu reste privé." },
    { question: "Quels outils SEO sont disponibles ?", answer: "Nous proposons plus de 17 outils, dont un générateur de balises Meta, un générateur de schémas, un générateur de sitemap, etc." },
    { question: "Puis-je utiliser ces outils pour des projets commerciaux ?", answer: "Oui, vous pouvez utiliser le code généré à n'importe quelle fin, y compris des projets commerciaux." },
    { question: "Comment améliorer le SEO de mon site ?", answer: "Commencez par de bonnes balises meta, ajoutez des données structurées, créez un sitemap et assurez-vous de configurer robots.txt." },
    { question: "Ces outils fonctionnent-ils sur mobile ?", answer: "Oui ! Tous les outils s'adaptent parfaitement aux mobiles et tablettes." }
  ],
  de: [
    { question: "Sind diese SEO-Tools wirklich kostenlos?", answer: "Ja! Alle Tools sind ohne Anmeldung komplett kostenlos nutzbar." },
    { question: "Sind meine Daten sicher?", answer: "Absolut. Alle Tools laufen in Ihrem Browser. Wir senden niemals Daten an einen Server." },
    { question: "Welche SEO-Tools sind verfügbar?", answer: "Wir bieten 17+ Tools, darunter Meta-Tag-Generator, Schema-Markup-Generator, Sitemap-Generator und viele mehr." },
    { question: "Kann ich diese Tools für kommerzielle Projekte nutzen?", answer: "Ja, Sie können den generierten Code für jeden Zweck nutzen, einschließlich kommerzieller Projekte." },
    { question: "Wie verbessere ich das SEO meiner Website?", answer: "Beginnen Sie mit korrekten Meta-Tags, fügen Sie strukturierte Daten hinzu, erstellen Sie eine Sitemap und konfigurieren Sie robots.txt." },
    { question: "Funktionieren diese Tools auf mobilen Geräten?", answer: "Ja! Alle Tools sind vollständig responsiv und funktionieren perfekt auf Smartphones." }
  ],
  it: [
    { question: "Questi strumenti SEO sono davvero gratuiti?", answer: "Sì! Tutti gli strumenti sono gratuiti e senza registrazione." },
    { question: "I miei dati sono al sicuro?", answer: "Assolutamente. Tutti gli strumenti funzionano nel tuo browser. Non inviamo mai dati ai nostri server." },
    { question: "Quali strumenti SEO sono disponibili?", answer: "Offriamo 17+ strumenti tra cui Generatore di Meta Tag, Generatore di Schema, Generatore di Sitemap e molti altri." },
    { question: "Posso utilizzare questi strumenti per progetti commerciali?", answer: "Sì, puoi usare il codice generato per qualsiasi scopo, inclusi progetti commerciali." },
    { question: "Come miglioro la SEO del mio sito?", answer: "Inizia con meta tag corretti, aggiungi dati strutturati, crea una sitemap e configura robots.txt." },
    { question: "Questi strumenti funzionano su dispositivi mobili?", answer: "Sì! Tutti gli strumenti sono responsive e funzionano perfettamente su smartphone e tablet." }
  ],
  pt: [
    { question: "Essas ferramentas SEO são realmente gratuitas?", answer: "Sim! Todas as ferramentas são totalmente gratuitas, sem necessidade de cadastro." },
    { question: "Meus dados estão seguros?", answer: "Absolutamente. Todas as ferramentas rodam no seu navegador. Nunca enviamos dados para nossos servidores." },
    { question: "Quais ferramentas SEO estão disponíveis?", answer: "Oferecemos mais de 17 ferramentas, incluindo Gerador de Meta Tags, Gerador de Schema, Gerador de Sitemap, etc." },
    { question: "Posso usar essas ferramentas em projetos comerciais?", answer: "Sim, você pode usar o código gerado para qualquer finalidade, incluindo projetos comerciais." },
    { question: "Como melhoro o SEO do meu site?", answer: "Comece com meta tags adequadas, adicione dados estruturados, crie um sitemap e garanta que o robots.txt esteja configurado corretamente." },
    { question: "Essas ferramentas funcionam em dispositivos móveis?", answer: "Sim! Todas as ferramentas são responsivas e funcionam perfeitamente no celular." }
  ]
};

const langs = ['en', 'es', 'fr', 'de', 'it', 'pt'];

langs.forEach(lang => {
  const filePath = path.join(__dirname, 'dictionaries', `${lang}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    if (!data.faq) data.faq = {};
    data.faq.questions = faqsTranslations[lang];
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated FAQ in ${lang}.json`);
  }
});
