import type { Metadata } from "next";
import Script from "next/script";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Link in Bio",
  description: "A social profile generated by SEO Utilities",
  robots: {
    index: false,
    follow: false,
  }
};

export default function BioLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="antialiased"
      suppressHydrationWarning
    >
      <body suppressHydrationWarning className="min-h-screen bg-background text-foreground">
        {children}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-VFWZTJQKC5"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-VFWZTJQKC5');
          `}
        </Script>
      </body>
    </html>
  );
}
