"use client";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const homeFAQs = [
  {
    question: "Are these SEO tools really free?",
    answer:
      "Yes! All tools on SEO Utilities are completely free to use with no sign-up required.",
  },
  {
    question: "Is my data safe? Do you store any information?",
    answer:
      "Absolutely. All tools run entirely in your browser. We never send your data to any server, and nothing is stored or logged. Your content stays private.",
  },
  {
    question: "What SEO tools are available?",
    answer:
      "We offer 17+ tools including Meta Tag Generator, Schema Markup Generator, Sitemap Generator, Robots.txt Generator, Keyword Density Checker, QR Code Generator, and many more. Each tool is designed to help with a specific aspect of SEO.",
  },
  {
    question: "Can I use these tools for commercial projects?",
    answer:
      "Yes, you can use the output generated by our tools for any purpose, including commercial projects. There are no restrictions on how you use the generated code or content.",
  },
  {
    question: "How do I improve my website's SEO?",
    answer:
      "Start with proper meta tags (use our Meta Tag Generator), add structured data (Schema Markup Generator), create a sitemap (Sitemap Generator), and ensure your robots.txt is properly configured. Each tool page includes specific SEO tips to help you get started.",
  },
  {
    question: "Do these tools work on mobile devices?",
    answer:
      "Yes! All tools are fully responsive and work perfectly on desktop, tablet, and mobile devices. The interface adapts to your screen size for the best experience.",
  },
];

export function FAQSection() {
  return (
    <section id="faq" className="scroll-mt-20">
      <div className="mb-8 text-center">
        <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
          Frequently Asked Questions
        </h2>
        <p className="mt-3 text-lg text-muted-foreground">
          Everything you need to know about SEO Utilities
        </p>
      </div>
      <div className="mx-auto max-w-3xl">
        <Accordion defaultValue={[]} className="w-full">
          {homeFAQs.map((faq, i) => (
            <AccordionItem key={i} value={`faq-${i}`}>
              <AccordionTrigger className="text-left text-base">
                {faq.question}
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground leading-relaxed">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
