import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata({
  title: "Terms of Service",
  description: "Read the terms and conditions for using SEO Utilities.",
  slug: "terms",
});

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <div className="prose prose-violet dark:prose-invert max-w-none">
        <h1 className="mb-6 text-4xl font-bold tracking-tight">Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: September 2, 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using SEO Utilities, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use our website.
        </p>

        <h2>2. Use License</h2>
        <p>
          We grant you permission to temporarily use the tools on SEO Utilities for personal or commercial purposes. This is the grant of a license, not a transfer of title.
        </p>
        <p>
          You may use the output generated by our tools (such as meta tags, schema markup, or sitemaps) on your own websites or client websites without attribution, though linking back to us is always appreciated.
        </p>

        <h2>3. Disclaimer</h2>
        <p>
          The materials on SEO Utilities are provided on an 'as is' basis. We make no warranties, expressed or implied, and hereby disclaim and negate all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
        </p>

        <h2>4. Limitations</h2>
        <p>
          In no event shall SEO Utilities or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on our website.
        </p>
      </div>
    </div>
  );
}
