import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata({
  title: "Terms of Service",
  description: "Terms of Service for SEO Utilities.",
  slug: "terms",
});

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <h1 className="mb-4 text-4xl font-bold tracking-tight">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">Last Updated: August 9, 2026</p>
      
      <div className="prose prose-violet dark:prose-invert max-w-none space-y-6 text-muted-foreground">
        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">1. Acceptance of Terms</h2>
        <p>
          By accessing and using SEO Utilities (seo-utilities.com), you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services.
        </p>

        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">2. Description of Service</h2>
        <p>
          SEO Utilities provides users with a collection of free, client-side webmaster and SEO tools. You understand and agree that the Service is provided "AS-IS" and that SEO Utilities assumes no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings.
        </p>

        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">3. Use of Generated Content</h2>
        <p>
          The code, metadata, and output generated by our tools (such as JSON-LD schema, meta tags, and robots.txt files) are free to use in your personal or commercial projects without restriction or attribution.
        </p>

        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">4. Limitations</h2>
        <p>
          In no event shall SEO Utilities or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on SEO Utilities' website.
        </p>
      </div>
    </div>
  );
}
